spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

twilio:
  enabled: false

server:
  port: 8080
